package com.example.ChoiGangDeliveryApp.enums;

public enum UserDeleteReason {

    HIGH_COSTS,
    SLOW_DELIVERY_TIMES,
    LACK_OF_VARIETY,
    DECLINING_FOOD_QUALITY,
    POOR_USER_EXPERIENCE,
    SECURITY_AND_PRIVACY_CONCERNS,
    POOR_CUSTOMER_SERVICE,
    UNATTRACTIVE_PROMOTIONS,
    OVERUSE_AND_NEED_TO_SAVE_MONEY,
    OTHER_REASONS

}
